import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import {
    DetectionExperiment,
    createDecoherenceDistribution,
    createDoubleSlitDistribution,
    createSeededRandom,
    createWhichPathDistribution,
    idealComplementarity,
    partialCoherenceMarkers,
    pathMarkerOverlap,
    sampleDetections
} from '../frontend/quantum-playground-model.mjs';

const geometry = {
    slitWidthM: 12e-6,
    slitSeparationM: 40e-6,
    wavelengthM: 550e-9,
    screenDistanceM: 1,
    detectorHalfWidthM: 0.05,
    binCount: 401
};

function assertArraysClose(actual, expected, tolerance = 1e-14) {
    assert.equal(actual.length, expected.length);
    for (let index = 0; index < actual.length; index += 1) {
        assert.ok(Math.abs(actual[index] - expected[index]) < tolerance, `bin ${index} differed`);
    }
}

test('gamma = 1 exactly reproduces Phase 2 and Phase 3 detector OFF', () => {
    const partial = createDecoherenceDistribution({ ...geometry, coherence: 1 });
    assertArraysClose(partial.probabilities, createDoubleSlitDistribution(geometry).probabilities);
    assertArraysClose(partial.probabilities, createWhichPathDistribution({ ...geometry, detectorEnabled: false }).probabilities);
});

test('gamma = 0 exactly reproduces Phase 3 detector ON', () => {
    const partial = createDecoherenceDistribution({ ...geometry, coherence: 0 });
    const measured = createWhichPathDistribution({ ...geometry, detectorEnabled: true });
    assertArraysClose(partial.probabilities, measured.probabilities);
    assertArraysClose(partial.interferenceTerms, measured.interferenceTerms);
});

test('intermediate gamma continuously scales the interference cross term', () => {
    const low = createDecoherenceDistribution({ ...geometry, coherence: 0.25 });
    const high = createDecoherenceDistribution({ ...geometry, coherence: 0.5 });
    for (let index = 0; index < low.interferenceTerms.length; index += 1) {
        assert.ok(Math.abs(high.interferenceTerms[index] - 2 * low.interferenceTerms[index]) < 1e-13);
    }
});

test('normalization and non-negativity hold across the full public slider range', () => {
    for (let step = 0; step <= 20; step += 1) {
        const distribution = createDecoherenceDistribution({ ...geometry, coherence: step / 20 });
        const total = distribution.probabilities.reduce((sum, value) => sum + value, 0);
        assert.ok(Math.abs(total - 1) < 1e-12);
        assert.ok(distribution.probabilities.every(value => value >= 0));
        assert.ok(distribution.intensities.every(value => value >= 0));
    }
});

test('constructed marker states are normalized and have the requested overlap', () => {
    for (const gamma of [0, 0.1, 0.35, 0.5, 0.9, 1]) {
        const markers = partialCoherenceMarkers(gamma);
        for (const marker of [markers.first, markers.second]) {
            assert.ok(Math.abs(marker.reduce((sum, value) => sum + value * value, 0) - 1) < 1e-14);
        }
        const overlap = pathMarkerOverlap(markers.first, markers.second);
        assert.ok(Math.abs(overlap.re - gamma) < 1e-14);
        assert.equal(overlap.im, 0);
    }
    assert.throws(() => partialCoherenceMarkers(-0.01), /between 0 and 1/);
    assert.throws(() => partialCoherenceMarkers(1.01), /between 0 and 1/);
});

test('default-geometry interference visibility changes monotonically with gamma', () => {
    let previous = -1;
    const center = Math.floor(geometry.binCount / 2);
    for (let step = 0; step <= 20; step += 1) {
        const gamma = step / 20;
        const distribution = createDecoherenceDistribution({ ...geometry, coherence: gamma });
        const visibility = Math.abs(distribution.interferenceTerms[center]) / distribution.incoherentIntensities[center];
        assert.ok(visibility >= previous - 1e-14);
        assert.ok(Math.abs(visibility - gamma) < 1e-14);
        previous = visibility;
    }
});

test('displayed ideal complementarity values satisfy V squared plus D squared equals one', () => {
    for (let step = 0; step <= 20; step += 1) {
        const { visibility, distinguishability } = idealComplementarity(step / 20);
        assert.ok(Math.abs(visibility ** 2 + distinguishability ** 2 - 1) < 1e-14);
    }
});

test('changing gamma clears observations generated by the previous distribution', () => {
    const experiment = new DetectionExperiment(createDecoherenceDistribution({ ...geometry, coherence: 1 }), 'phase-4-state');
    experiment.emit(1000);
    assert.equal(experiment.total, 1000);
    experiment.setDistribution(createDecoherenceDistribution({ ...geometry, coherence: 0.45 }));
    assert.equal(experiment.total, 0);
    assert.equal(experiment.recent.length, 0);
    assert.ok(experiment.counts.every(count => count === 0));

    const controller = readFileSync(new URL('../frontend/quantum-playground.js', import.meta.url), 'utf8');
    assert.match(controller, /updateDecoherence\(\)[\s\S]*rebuildDecoherenceDistribution\(\)[\s\S]*this\.reset\(\)/);
});

test('seeded partial-coherence samples remain reproducible', () => {
    const distribution = createDecoherenceDistribution({ ...geometry, coherence: 0.45 });
    const first = sampleDetections(distribution, 5000, createSeededRandom('phase-4-sampling'));
    const second = sampleDetections(distribution, 5000, createSeededRandom('phase-4-sampling'));
    assert.deepEqual([...first], [...second]);
    assert.ok(new Set(first).size > 40);
});

test('Phase 4 UI and education expose ideal complementarity without claiming microscopic identity', () => {
    const page = readFileSync(new URL('../frontend/quantum-playground.html', import.meta.url), 'utf8');
    assert.match(page, /data-experiment="decoherence"[^>]*>[\s\S]*?<span>Live<\/span>/);
    assert.match(page, /id="quantum-coherence" type="range" min="0" max="1" step="0\.05"/);
    assert.match(page, /V² \+ D² = 1/);
    assert.match(page, /V² \+ D² ≤ 1/);

    const controller = readFileSync(new URL('../frontend/quantum-playground.js', import.meta.url), 'utf8');
    assert.match(controller, /off-diagonal terms in the reduced path density matrix/);
    assert.match(controller, /without being microscopically identical processes/);
    assert.doesNotMatch(controller, /microscopic environmental dynamics/i);
});
